### ISSUE TITLE
Laravel 10 and 11 support

### ISSUE THREAD

**Issue by stefanrakicfaxi** [LowerRockLabs/laravel-lockable#29]
Please add Laravel 10 and 11 support

**Comment by lrljoe** [comment]
Will do this weekend!  Apologies, didn't realise it was being actively used!

**Comment by lrljoe** [comment]
@stefanrakicfaxi  - Done, and updated the dependencies to remove known vulnerable versions.

I'll add a couple more bits into it shortly, namely:

1. Translated Localisations
2. Config option to either use UUIDs for Models/Users or not
3. TypeHinting where it's missing.

Is there any feature/hook that you want adding in?
